name: uok_chatbot

services:
  backend:
    build:
      context: ./Backend/Chatbot
      dockerfile: Dockerfile
    container_name: chatbot_app
    volumes:
      - ./Backend/Chatbot:/Chatbot
    ports:
      - "8000:8080"
    env_file:
      - ./Backend/Chatbot/.env
    environment:
      DJANGO_SETTINGS_MODULE: Chatbot.settings
      REDIS_PUBLIC_URL: redis://redis:6379/0
      DATABASE_URL: postgresql+psycopg://ai:ai@pgvector:5432/ai
    depends_on:
      - pgvector
      - redis

  celery:
    build:
      context: ./Backend/Chatbot
      dockerfile: Dockerfile
    container_name: chatbot_celery
    command: celery -A Chatbot worker --loglevel=info --concurrency=2
    volumes:
      - ./Backend/Chatbot:/Chatbot
    env_file:
      - ./Backend/Chatbot/.env
    environment:
      DJANGO_SETTINGS_MODULE: Chatbot.settings
      REDIS_PUBLIC_URL: redis://redis:6379/0
      DATABASE_URL: postgresql+psycopg://ai:ai@pgvector:5432/ai
    depends_on:
      - pgvector
      - backend
      - redis

  pgvector:
    image: phidata/pgvector:16
    container_name: pgvectorDev
    environment:
      POSTGRES_DB: ai
      POSTGRES_USER: ai
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5532:5432"
    volumes:
      - pgvolume:/var/lib/postgresql/data

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./frontend:/frontend/src
    environment:
      VITE_GOOGLE_CLIENT_ID: ${VITE_GOOGLE_CLIENT_ID}
    depends_on:
      - backend
  redis:
    image: redis:7-alpine
    container_name: chatbot_redis
    ports:
      - "6379:6379"

volumes:
  pgvolume: