# Generated by Django 5.2.3 on 2025-12-18 16:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapi', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadrecord',
            name='file_name',
        ),
        migrations.RemoveField(
            model_name='uploadrecord',
            name='inserted',
        ),
        migrations.RemoveField(
            model_name='uploadrecord',
            name='skipped',
        ),
        migrations.AddField(
            model_name='uploadrecord',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='pdfs/'),
        ),
        migrations.AddField(
            model_name='uploadrecord',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='uploadrecord',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
