# Generated by Django 6.0 on 2026-01-01 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatapi', '0002_remove_uploadrecord_file_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='KnowledgeBase',
        ),
    ]
