# Generated by Django 6.0 on 2026-02-22 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapi', '0003_delete_knowledgebase'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadrecord',
            name='processed_chunks',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='uploadrecord',
            name='status',
            field=models.CharField(choices=[('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='processing', max_length=100),
        ),
        migrations.AddField(
            model_name='uploadrecord',
            name='total_chunks',
            field=models.IntegerField(default=0),
        ),
    ]
