# Generated by Django 6.0.3 on 2026-04-24 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapi', '0004_uploadrecord_processed_chunks_uploadrecord_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='session_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
