# Generated by Django 6.0.3 on 2026-04-24 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapi', '0005_chatmessage_session_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='session_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
    ]
